GCOV_PROFILE := y
#
# Makefile for the video capture/playback device drivers.
#
obj-y				+= avp/
obj-$(CONFIG_TEGRA_MEDIASERVER)	+= mediaserver/
obj-$(CONFIG_TEGRA_NVAVP)	+= nvavp/
obj-$(CONFIG_TEGRA_DTV)		+= tegra_dtv.o
obj-$(CONFIG_TEGRA_CAMERA)	+= tegra_camera.o
obj-$(CONFIG_VIDEO_S5K4ECGX)    += s5k4ecgx.o
obj-$(CONFIG_VIDEO_S5K6AAFX)    += s5k6aafx.o
obj-$(CONFIG_VIDEO_M5MO)        += m5mo.o

