# drivers/media/video/samsung/mhl_v1/Makefile
#
# Copyright (c) 2010 Samsung Electronics Co., Ltd.
# 		http://www.samsung.com/
# Woojong Yoo
#	woojong.yoo@samsung.com
# Licensed under GPLv2


obj-$(CONFIG_MHL_SII9234) +=	mhl/
